name: Library SQL Assignment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  autograding:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Give Execute Permission
        run: chmod +x tests/test.sh

      - name: Execute Tests
        run: ./tests/test.sh
